### PR TITLE
feat: add GPN card

### LINKED ISSUE #89: Add support for card GPN
Hello,

I would like to identify card from GPN. You can get GPN traits on [Wikipedia](https://en.wikipedia.org/wiki/Payment_card_number#Issuer_identification_number_%28IIN%29).

If you want to solve this issue, check this [how-to guide]( https://github.com/d-edge/Cardidy/blob/main/CONTRIBUTING.md#add-a-new-card).

Cheers,

### PR DESCRIPTION
**Pull request by blouflashdb**
Closes #89

### CODE REVIEW

**Review by aloisdg — APPROVED** [review]
Looks good to me :)

**Comment by aloisdg** [comment]
@blouflashdb [Hacktoberfest](https://hacktoberfest.com/) has not yet begun, should I hold off on this pull requests until October so they can count or should I merge it right away?

**Review by torendil — APPROVED** [review]
LTGM too :)

**Comment by blouflashdb** [comment]
Please hold it off until october

**Comment by aloisdg** [comment]
No problem we will do that. Thanks again for your contribution :)

**Comment by aloisdg** [comment]
Merged! It should be visible in the website:

image

**Pull request merged**
