### PR TITLE
feat: add Support for NPS Pridnestrovie

### LINKED ISSUE #19: Add support for NPS Pridnestrovie
Hello,

I would like to identify card from NPS Pridnestrovie. You can get NPS Pridnestrovie traits on [Wikipedia](https://en.wikipedia.org/wiki/Payment_card_number#Issuer_identification_number_%28IIN%29).

If you want to solve this issue, check this [how-to guide](https://github.com/d-edge/Cardidy/blob/main/CONTRIBUTING.md#add-a-new-card).

Cheers,

### PR DESCRIPTION
**Pull request by ntbm**
Closes #19

### CODE REVIEW

**Review by aloisdg — DISMISSED** [review]
Looks good to me :)

Thank for your work

**Comment by ntbm** [comment]
@aloisdg As you require verified commits in this repo. I repushed a signed version of the commits.

**Comment by blouflashdb** [comment]
A test case for IIN Range 6054743 is missing.

**Comment by ntbm** [comment]
@blouflashdb Thanks for the hint. Added the missing test

**Review by aloisdg — APPROVED** [review]

**Comment by aloisdg** [comment]
Nice catch @blouflashdb

**Review by torendil — DISMISSED** [review]
LGTM

**Review by aloisdg — APPROVED** [review]

**Comment by aloisdg** [comment]
Let's merge that

**Pull request merged**
